development:
  africastalking:
    api_key: da186e1964ca22b05cdd4eba65ddec3281c23c9b2ebdf8fb27151160ae5c9bc8
    username: sandbox
test:
  africastalking:
    api_key:
    username: sandbox
production:
  africastalking:
    api_key:
    username: