development:
  admin_email: philipwafula2@gmail.com
  admin_password: password
  domain_name:
  k2_api_key: 3605be38efbd3503e9c366f8bb44e96f8d9995ec85efeaebb4a93ac0
  sms_gateway_endpoint: https://api.sandbox.africastalking.com/version1/messaging # https://api.africastalking.com/version1/messaging
  sms_gateway_username: sandbox
  sms_gateway_api_key: 192754b97b793c7ec27ea8080d4f82cb518fa0cb7610a7c23e5433acb1807692
test:
  admin_email: philipwafula2@gmail.com
  admin_password: password
  domain_name:
  k2_api_key:
  sms_gateway_endpoint: https://api.sandbox.africastalking.com/version1/messaging # https://api.africastalking.com/version1/messaging
  sms_gateway_username: sandbox
  sms_gateway_api_key: 192754b97b793c7ec27ea8080d4f82cb518fa0cb7610a7c23e5433acb1807692
production:
  admin_email: ongawobrian@gmail.com
  admin_password: password
  mailer_domain_name: heroku.com
  k2_api_key: 9015c28b17c4a412246a1278d6e15fa4c3865fa4
  sms_gateway_endpoint: https://api.africastalking.com/version1/messaging
  sms_gateway_username: ongawobrian
  sms_gateway_api_key: e13f14e4c46d5758ecf7780434733cff9b002e53fc360233f1a4280d40228fc0
  heroku_send_grid_username: app135017920@heroku.com
  heroku_send_grid_password: 5w3bynjd2403