development:
  admin_email: email@domain.com
  admin_password: change_me
  domain_name: domain
  k2_api_key:
  sms_gateway_endpoint:
  sms_gateway_username:
  sms_gateway_api_key:
test:
  admin_email:
  admin_password:
  domain_name:
  k2_api_key:
  sms_gateway_endpoint:
  sms_gateway_username:
  sms_gateway_api_key:
production:
  admin_email:
  admin_password:
  mailer_domain_name:
  k2_api_key:
  sms_gateway_endpoint:
  sms_gateway_username:
  sms_gateway_api_key:
  heroku_send_grid_username:
  heroku_send_grid_password: