development:
  admin_email: philipwafula2@gmail.com
  admin_password: password
  k2_api_key: 3605be38efbd3503e9c366f8bb44e96f8d9995ec85efeaebb4a93ac0
  sms_gateway_endpoint: https://api.sandbox.africastalking.com/version1/messaging # https://api.africastalking.com/version1/messaging
  sms_gateway_username: sandbox
  sms_gateway_api_key: 192754b97b793c7ec27ea8080d4f82cb518fa0cb7610a7c23e5433acb1807692
  domain_name: heroku.com
  email_provider_username: wanga.philip.devwork@gmail.com
  email_provider_password: sct211-0072/2016
test:
  k2_api_key:
production:
  k2_api_key: